### ISSUE TITLE
container network utilization widget does not work

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#105]

**Comment by spiermar** [comment]
Waiting to test with PCP 3.10.8.

**Comment by natoscott** [comment]
| Waiting to test with PCP 3.10.8.

Bit of background - the container network stats require a container name to be set on a pcp context, one way or another, and can't be intuited from the cgroup metrics like some other stats can.  

This equates to access either via the /pmapi/context?hostspec=xxx setting (i.e. the old model: many containers == many pcp contexts) or dynamically via the storable pmcd.client.container metric (i.e. the new model: many containers via one pcp context).

Everything else needed is in place for accessing multiple containers from one pcp context now in pcp-3.10.8, however the pmwebd support for actually switching containers on-the-fly is unfortunately lacking at this stage.  pmwebd will need to learn about the pmStore(3) interface and the PM_CTXFLAG_EXCLUSIVE option to make this happen.  Regular C client tools can do this, but not yet web applications.

Also, Frank seems to be reluctant to implement the pmwebapi _store interface for web clients, so that code is likely to have to come from elsewhere - someone from the Red Hat PCP development team will step up if it doesn't happen in a release or so, but help from others would be ideal (and much quicker, at this stage).  See the 'METRIC STORE' section in the pmwebapi(3) man page for details & feel free to ping me for more detail if anyone wants to hack on it.

In the meantime, Vector could revisit using individual-contexts-for-every-container, which works just as it did before pcp-3.10.8 - but, AIUI from Henry, the large number of contexts makes that a non-starter for Vector requests from a browser and would be a more complex implementation anyway.

**Comment by fche** [comment]
"Vector could revisit using individual-contexts-for-every-container, which works just as it did before pcp-3.10.8 - but, AIUI from Henry, the large number of contexts makes that a non-starter for Vector requests from a browser"

I would appreciate some substantiation about this analysis.  Given that pmwebd is single-threaded, it will only service one /pmapi/ call at a time, no matter how many contexts are open by the webapp.  If anything, increased traffic due to pmstore/pmfetch pairs would _reduce_ the webapp<->pmwebd performance.

**Comment by natoscott** [comment]
| Given that pmwebd is single-threaded,

I think this assumption that this change is being driven by pmwebd performance is confusing things for you - multi/single-threaded-ness is irrelevant here.

| both in terms of bandwidth, there being more messages, 

It may help to think in terms of how tools (webapps/binaries - it doesn't matter) will be using the data they retrieve, rather than implementation details in the current version of pmwebd and preconceived ideas about pmstore being evil.  Problems stem from the way containers are queried and reported more like processes (moving targets - dynamic instances in PCP parlance) as opposed to disks/cpus (largely static instance domains, which are not typically re-evaluated on every sample).

If you're following that, you will see that contexts would need to be created & torn down frequently in the one-context-per-container model - on every sample (setting aside the coding pain of having to manage so many contexts at once - potentially hundreds/thousands - a very valid concern the Vector folks have expressed).  And if you understand what is involved in PCP protocol exchange at context creation time (many times heavier-weight than a store operation on an existing context), it should be clear why hundreds/thousands of rapidly evolving pmwebapi contexts is not a viable solution.

There were other Vector/browser reasons too that Henry alluded to - hopefully he will chime in here and describe those further.

| and latency, there being a necessary ordering / synchronization between messages

Context creation and teardown involves far more PCP protocol messages than store (not to mention TCP connection setup/negotiation/teardown, thousands of times).

Anyway - the most scientific approach now would be for someone to code up _store API support in pmwebd so we can try it out.  Then the Vector folks can compare/contrast things for us and see what suits best.  If you aren't interested @fche (?) I'll add it to my list, or see if I can find someone else.

**Comment by natoscott** [comment]
| Anyway - the most scientific approach now would be for someone to code up _store API support

See: git://git.pcp.io/nathans/pcp.git master

The pmwebapi(3) man page describes the _store interface, which is available for all of the PCP metrics that support the PCP pmStore(3) interface.

For our purposes here, with this latest code its possible to switch between containers dynamically from a single pmwebapi context, by issuing "_store?name=pmcd.client.container&value=[ContainerID]"

I'm keen to hear how it goes, and especially any experiences contrasting this new access method with the old multiple-contexts-for-multiple-containers method - thanks!

**Comment by fche** [comment]
"this assumption that this change is being driven by pmwebd performance is confusing things"

Not _pmwebd_ performance, _application_ performance.  Is that judged not to matter, but instead "application complexity" is the perceived driver here?


"contexts would need to be created & torn down frequently in the one-context-per-container model - on every sample"

Of course not _on every sample_.  If one expects to take more than _one sample per container lifetime_, then one pays the setup cost -once-, and reuses the context for consequent sample fetches.  A one-time connection-setup handshake can be amortized, even if relatively slow.  What is your expected sampling-interval to container-lifespan ratio?


"(setting aside the coding pain of having to manage so many contexts at once - potentially hundreds/thousands"

There exist data structures called lookup tables that can store string to integer mappings, even hundreds/thousands of them.


"Anyway - the most scientific approach now would be for someone to code up _store API support in pmwebd so we can try it out."

No, pmwebd is a distraction here.  Exactly the same phenomena (bandwidth & latency penalties in reasonable cases) are in play if one talks directly to pmcd.  It is just as single-threaded / sequential.

**Comment by hc000** [comment]
@natoscott @fche there is a limitation for the browser to only make 6 concurrent http request per second. If each container requires their own context, it would be its own individual request. And since there can be hundreds of containers per server, it would be hundreds of context. Although I think anything more than 6 is put into a queue. But this would mess with the intervals depending on how many containers there are.

**Comment by fche** [comment]
@hc000, Each pmwebapi operation (set / fetch / new-context) is its own individual http request / connection.  Therefore, minimizing number of messages is key.  Using a single pmwebapi context, and pmstore/pmfetch pairing all the time _increases_ the required number of http messages (as compared with reusing per-container context and pmfetch'ing only), and thus hurts both bandwidth & latency performance.

**Comment by natoscott** [comment]
@hc000  @spiermar  the Vector code can be implemented either way now (pmwebd _store support will be merged into pcp master branch today), so please experiment and report back with actual experiences.

ISTM we need to get more of a feel for the cost of establishing/tearing down contexts (which are very high on the back end) vs _store access (which is relatively cheap on the backend), and the likelihood of having a dynamically-changing set of containers vs having a stable set - I think the former more likely, like processes, but evidently that's not universally agreed.

Also, there are many other potential strategies we can use here, which make dynamic context switching even more attractive. For example, we can use the cgroup CPU accounting metrics to cull potentially large numbers of either inactive, or much-less-active, containers from the set that we actually query network stats for (the network metrics requiring container/namespace switching, one way or the other, but  the CPU metrics use cgroups, which do not).  This was what I was referring to in earlier comments about top-like behaviour and the dynamic nature of per-process monitoring.  In this model, _store and dynamic switching wins hands down for rapidly changing sets of top-containers - fewer messages at *both* the back end (pcp messages) and front end (http messages), and will result in simpler application code.

FWIW, hacking on pmwebd recently I came across once more the number of inefficiencies it has with its own communications with pmcd, so its entirely possible latency at the frontend will also easily be hidden by overwhelming protocol exchange costs at the backend, for example.  (Martin, the high CPU count issue you observed is quite possibly a result of this.)

So take all of the earlier comments with a grain of salt - there are lots of interesting theories there, all needing data to back them up - both access models will be available, and if neither suits we can even look into other server-side filtering options (maybe new PMDAs, maybe things like hotproc.* for containers) now that pmwebd _store support is becoming available.

I'll begin looking into addressing some of those pmwebapi backend inefficiencies (amongst other improvements) in the new year - its going to need a fair bit of work though, so not a short term thing.

**Comment by fche** [comment]
"In this model, _store and dynamic switching wins hands down for rapidly changing sets of top-containers - fewer messages at both the back end (pcp messages) and front end (http messages)"

What matters is not the changeability of the set of containers, but the payload (number of fetches) targeted to any given container (no matter when it is born / dies).  As soon as that latter number starts climbing above ~2 (a number depending on actual latencies), a dedicated context starts winning in bandwidth+latency again.  Trace the sequence of calls and see.

(This is independent of other pmwebd optimizations.)

**Comment by spiermar** [comment]
Deploying 3.10.8 to test.

**Comment by spiermar** [comment]
We have a working widget that provides access to the network interfaces, including container ones. At this point, data is there, but we need to resolve the interface to the container name/id. Work will be tracked on a different issue. 
https://github.com/Netflix/vector/issues/119
