### ISSUE TITLE
Monitor docker containers

### ISSUE THREAD

**Issue by panda87** [Netflix/vector#113]
Hi

There is a way to monitor specific docker container stats from Vector?
I have many docker containers on one machine and I wonder if Vector can give me stats per specific docker container

Thanks
D.

**Comment by spiermar** [comment]
Hi @panda87 
We're still testing the set of features that will enable users to have better support for monitoring containers. Right now, the features are in, but disabled by default because of a few bugs.
To summarize the features, we have a few container-specific widgets (for CPU, disk and network IO, etc) that will display these metrics for all containers running in a host. There's also a global filter that can help you isolate the containers you're monitoring.

Is that what you are looking for?

p.s.: see https://github.com/Netflix/vector/issues/66

**Comment by hc000** [comment]
@panda87:

As spiermar mentioned, there are some container specific widgets already in vector, but not all of the metrics are implemented.
If you follow the steps here from the getting started guide: https://github.com/Netflix/vector/wiki/Getting-Started and after cloning vector, check out the container-popup branch which has the latest container specific code.

You should be able to see the container widgets on the drop down.

**Comment by panda87** [comment]
@spiermar Yes, this is what I look for.
@hc000 mmmm, so you are saying that once I clone the latest master branch, I will be able to choose the container name from drop down list for CPU, mem etc. metrics?

**Comment by spiermar** [comment]
I already merged some of the changes into master, so yes, you should be able to get those in master, but you need to set the "enableContainerWidgets" flag to true in "app.config.js". The "container-popup" branch has a few more changes that should be merged soon.

**Comment by panda87** [comment]
Thanks, I'll try to take a look in the next few days.
@spiermar when do you think this will be merged?

**Comment by spiermar** [comment]
Haven't checked the changes yet, but if it's nothing that will break current functionality, I can merge and test pretty quickly.

**Comment by spiermar** [comment]
I'm assuming this issue is closed. Let me know if otherwise and I'll reopen.
