### ISSUE TITLE
Flamegraphs options not enabled despite default configure is set to true

### ISSUE THREAD

**Issue by itsdax** [Netflix/vector#213]
Flame graphs seem to not be enabled, and when clicking flamegraphs on the simple dashboard view, no data is being shown.

Is there still a dependency for [vector-pmda](https://github.com/spiermar/vector-pmda) to enable this feature? I'm currently unable to find any official details/docs for enabling the flamegraphs feature

Tested on v2.0.0-beta.1

**Comment by jasonk000** [comment]
@itsdax yes, there is still a dependency for vector-pmda in order to enable this, and you'll also need to ensure you have the configuration flag `enableFlamegraphs: true` set in `src/app/config.js` at build time.

If the widget is not visible, it means you have not included it in the build. If the widget is visible but greyed out, it means that Vector did not detect the PMDA running on the target system.
