### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by j-white** [Netflix/vector#59]
The blog post mentions Cassandra as one of the possible next steps. What did you envision here?

I think it would be a great fit for http://newts.io and could contribute an integration.

Metrics would be pushed to Cassandra via Newts as they are collected and later analyzed or graphed.

**Comment by spiermar** [comment]
Not exactly that. In order to minimize impact on monitored systems (and cost), we opted to avoid persisting (or even collecting) metrics from systems that are not currently being looked at. There are other options that are well integrated with PCP, like Grafana, that can be used for that.
We're considering adding support for explicitly persist metrics for specific hosts, and only for a limited time window. At our scale it's not cost-effective to persist that amount of metrics at high-resolution for all hosts we have.
When I mentioned Cassandra in the blog post, what I meant was a Cassandra focused metric agent and dashboard on Vector. The goal is to better monitor Cassandra clusters in real-time.

**Comment by j-white** [comment]
Thanks for the clarification!
