### ISSUE TITLE
improve project structure

### ISSUE THREAD

**Issue by spiermar** [Netflix/vector#8]
* AngularJS styleguide:
  * https://github.com/toddmotto/angularjs-styleguide
* Move dependencies to sub-modules
* Rename factories.js to metrics.js
* Remove unused vector.js
* Rename ngDelay directive
* Remove directive "replace: true" option
* Directive restrict to A instead of E

**Comment by dylanjohnson** [comment]
:+1: 

:100: for automating with [angularjs-eslint](https://github.com/Gillespie59/angularjs-eslint). I'd be happy to submit a PR that adds it to the gulpfile.

**Comment by spiermar** [comment]
go ahead @dylanjohnson ! tks

**Comment by meteorfox** [comment]
Are there strong reasons in following Todd Motto's style guide? I understand this a matter of personal preference, and convention, but my impression after seeing some Angular projects out there, seems to me most follow  a mix of Todd and [John Papa's style guide](https://github.com/johnpapa/angular-styleguide), usually leaning to papa's style guide, either way, both agree on most things. 

Personally, I mostly follow, [john papa's style guide](https://github.com/johnpapa/angular-styleguide), since I like the view of organizing code that reads like a 'newspaper articles', essence on the top, details at the bottom.

**Comment by spiermar** [comment]
@meteorfox no strong reasons. Either Todd or John's would be better than what we have right now, I'm just a bit more familiar with Todd's.

**Comment by meteorfox** [comment]
Sounds good, I'll follow Todd's style guide and the eslint suggestions. Thanks

**Comment by spiermar** [comment]
@zanthrash any comments?

**Comment by zanthrash** [comment]
@spiermar I personally use Todd's.  But both are good.

**Comment by meteorfox** [comment]
I have another working branch, which a little more ambitious refactor that builts on top #39, but currently works.

It changes the whole project structure to use layout and automation of  [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular).
- This add all the functionality of  generator-gulp-angular
- so, minification, protractor, karma, uglification, gulp-inject, 'prod' dist, browser live refreshes, jshint build step, etc

Feel free to this branch from my personal repo:
https://github.com/meteorfox/vector/tree/generator-angular-gulp-refactor

Simply `git clone`, then `cd` and `npm install` followed by `bower install`. Finally, just `gulp serve`

**Comment by spiermar** [comment]
Merged and it looks fine. I'll try to break factories, widgets and datamodels and use the same structure. Once that's done we can look into a larger refactor, but I like it. ;-)

**Comment by spiermar** [comment]
Just pushed a few more changes. Looks a bit better. Let me know what you think @meteorfox @dylanjohnson @zanthrash

**Comment by meteorfox** [comment]
@spiermar looks beautiful! :)
