### ISSUE TITLE
firefox rendering bug: individual widget charts clipped at 150px tall

### ISSUE THREAD

**Issue by fche** [Netflix/vector#83]
On firefox 40.0.3 (Fedora21), every widget appears clipped to the top 150 pixels, dropping the bottom axis & labels.  Chrome & epiphany on same platform seem fine.  Browsing with firebug unfortunately not enough for this newb to diagnose the cause.  It appears to be a regression in 1.0.2 since 1.0.1.
![vector-1 0 2-format](https://cloud.githubusercontent.com/assets/588885/9911750/32c2f7fa-5c93-11e5-8e4e-2c80aca559f4.png)

**Comment by fche** [comment]
This problem persists to git master vector, not just the v1.0.2 release.

**Comment by hc000** [comment]
I think there is a difference in the way firefox implements svg vs chrome.
To fix this problem in firefox, just need to set the size with px instead of %

<img width="1128" alt="screen shot 2015-09-16 at 10 50 50 am" src="https://cloud.githubusercontent.com/assets/3950207/9913270/dbca99b2-5c60-11e5-9096-aee32ea7049d.png">

**Comment by spiermar** [comment]
Interesting. The 100% is coming from the default nvd3 css. There's an inline element style setting the px value, but Firefox is ignoring it. That's why FF is trying to use the % value.
I'm using inline because this is calculated based on the widget config. Have to figure out why FF is ignoring it.
![screen shot 2015-09-16 at 1 32 14 pm](https://cloud.githubusercontent.com/assets/2207415/9917616/7757e20c-5c77-11e5-814e-3d45ac6b6f9e.png)
<img width="648" alt="screen shot 2015-09-16 at 1 32 49 pm" src="https://cloud.githubusercontent.com/assets/2207415/9917617/7759a93e-5c77-11e5-9066-dc0f6d23d2a8.png">

**Comment by spiermar** [comment]
Setting the style manually works, but for some reason, d3 is not setting it on FF.

This should take care of setting the inline style:
https://github.com/Netflix/vector/blob/ecfcd08c490ab01ae4c8bc120b4791a9ac396303/src/app/charts/line-timeseries.directive.js#L70

**Comment by spiermar** [comment]
Fixed it, just waiting to get my access back. Was away for so long they forgot about me. :-)

**Comment by spiermar** [comment]
https://github.com/Netflix/vector/commit/2a6f45c38c42b015ecd94792e501ea49d9c124b0

Can you check @fche ?

**Comment by fche** [comment]
That does it, thanks!

**Comment by fche** [comment]
(Aw man, still seing the phenomenon on -some- of the charts.  Investigating.)

**Comment by hc000** [comment]
@fche I just made a commit, can you try now?

**Comment by spiermar** [comment]
Oops, misse the stacked charts. Tks @hc000 !

**Comment by spiermar** [comment]
Assuming this is working now. Closing the issue, but let me know if I'm wrong. ;-)
